version: "3"
services:
  mongodb:
    image: mongo:4.2.21-bionic
    container_name: mongodb_dev
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    ports:
      - 27017:27017
    restart: always
    volumes:
      - mongodb:/data

volumes:
  mongodb:
    driver: local
